apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-client-test
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: management
  namespace: kubernetes-client-test
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-apiserver-url-root
rules:
  - nonResourceURLs:
      - /
    verbs:
      - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-apiserver-url-root
subjects:
- kind: ServiceAccount
  name: management
  namespace: kubernetes-client-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-apiserver-url-root
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: get-namespaces
subjects:
- kind: ServiceAccount
  name: management
  namespace: kubernetes-client-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: get-namespaces
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kubernetes-client-test
  namespace: kubernetes-client-test
  labels:
    app: kubernetes-client-test
    version: latest
spec:
  selector:
    matchLabels:
      app: kubernetes-client-test
  template:
    metadata:
      labels:
        app: kubernetes-client-test
    spec:
      serviceAccountName: management
      containers:
      - name: kubernetes-client-test
        image: quay.io/skedulo/kubernetes-client-test
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
